application-version: '@project.version@'

spring:
  application:
    name: woofles
  config:
    import:
      - optional:file:.env[.properties]
      - vault://

  datasource:
    username: ${db_user}
    password: ${db_password}
    url: jdbc:postgresql://localhost:5432/woofles
  jpa:
    hibernate:
      ddl-auto: none

  cloud:
    vault:
      scheme: http
      token: ${VAULT_TOKEN} # from GitHub secrets
      host: 172.17.0.1 # docker host ip

  mail:
    host: smtp.mailgun.org
    password: ${mail_password}
    port: 587
    username: postmaster@woofl.es

  thymeleaf:
    cache: false
    mode: HTML

mailgun:
  apikey: ${mailgun_apikey}
  url: https://api.mailgun.net/v3/woofl.es

rememberme-key: ${rememberme-key}

--- # dev properties
spring:
  config.activate.on-profile: dev
  cloud:
    vault:
      host: 192.168.188.73
      token: null # from ~/.vault-token

  datasource.url: jdbc:postgresql://192.168.188.73:5432/woofles
  jpa.show-sql: true

rememberme-key: remember-dev
