application-version: '@project.version@'

spring:
  application:
    name: woofles
  config:
    import:
      - optional:file:.env[.properties]

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST:172.17.0.1}:${DB_PORT:5432}/woofles
  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.mailgun.org
    password: ${MAIL_PASSWORD}
    port: 587
    username: postmaster@woofl.es

  thymeleaf:
    cache: false
    mode: HTML

mailgun:
  apikey: ${MAILGUN_APIKEY}
  url: https://api.mailgun.net/v3/woofl.es

turnstile.secret: ${TURNSTILE_SECRET}
rememberme-key: ${REMEMBERME_KEY}

--- # dev properties
spring:
  config.activate.on-profile: dev
  datasource.url: jdbc:postgresql://${DB_HOST:192.168.188.73}:${DB_PORT:5432}/woofles
  jpa.show-sql: true

rememberme-key: remember-dev
