CREATE TABLE IF NOT EXISTS role (
  `role_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`)
);
DELETE FROM role;
INSERT INTO role VALUES (1, 'admin');
INSERT INTO role VALUES (2, 'user');